name: CI

on:
  push:
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  build:
    # if: github.event_name == 'push' || github.event.pull_request.head.repo.id != github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET SDK v7.0.306
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.306
      - name: Build
        run: dotnet build

  publish-release:
    # if: ${{ !github.event.repository.fork && startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ github.ref_name }}"
